{
 "title": "First Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pipeline",
    "label": "Pipeline Name",
    "query": "SELECT distinct(\"project_name\") FROM \"jenkins_data\""
   }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "jenkins_data",
     "query": "SELECT 1 FROM \"autogen\".\"job\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "project_build_health" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$pipeline$/" }
     ]
    }
   ]
  },
  {
   "title": "Build Result Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Build Status: $tag_build_result",
     "groupBy": [
      { "params": [ "build_result" ], "type": "tag" }
     ],
     "measurement": "jenkins_data",
     "select": [
      [
       { "params": [ "build_result" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Build List",
   "type": "table",
   "gridPos": { "h": 19, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "measurement": "jenkins_data",
     "query": "SELECT \"project_name\", \"build_result\", \"build_time\"  / 1000 FROM \"autogen\".\"jenkins_data\" WHERE (\"project_name\" =~ /^$pipeline$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "build_result" ], "type": "field" }
      ],
      [
       { "params": [ "build_time" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ],
      [
       { "params": [ "project_name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$pipeline$/" }
     ]
    }
   ]
  },
  {
   "title": "CI Performance Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Buid Time - $tag_project_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "project_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jenkins_data",
     "query": "SELECT distinct(\"build_time\")  / 1000 FROM \"autogen\".\"jenkins_data\" WHERE (\"project_name\" = 'first_pipeline') AND $timeFilter GROUP BY time($__interval), \"project_name\" fill(0)",
     "select": [
      [
       { "params": [ "build_time" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$pipeline$/" }
     ]
    }
   ]
  }
 ]
}